#spring:
#  application:
#    name: backend

spring:
  application:
    name: LLHelper

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/LL_Helper}
    username: ${DB_USERNAME:troloko}
    password: ${DB_PASSWORD:1111}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:default-dev-secret-must-be-32-chars-long}
  expiration: ${JWT_EXPIRATION:86400000}